apiVersion: v1
kind: Pod
metadata:
   name: purity-rest-tool-pod
spec:
   containers:
   - name: purity-rest-tool-container01
     image: buildanddestroy/purity-rest-tool:latest
     ports:
     - containerPort: 6379
